UPDATE centro SET latitud=40.4486898, longitud=-3.722631  where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ de ramiro de maeztu madrid 28040';
UPDATE centro SET latitud=40.1934983, longitud=-3.670162  where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' '))) in ('c/ felipe ii valdemoro', 'c/ felipe ii, s/n valdemoro 28341');
UPDATE centro SET latitud=40.3366831, longitud=-3.820752  where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ institutos, s/n alcorcón 28923';
UPDATE centro SET latitud=40.3142334, longitud=-3.784507  where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ del alcalde francisco moreno menéndez, 18 leganés 28914';
UPDATE centro SET latitud=40.4309291, longitud=-3.848330  where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ transversal cuatro, 4 pozuelo de alarcón';
UPDATE centro SET latitud=40.3156473, longitud=-3.4778198 where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='del niño jesús, 1 arganda del rey 28500';
UPDATE centro SET latitud=40.3533998, longitud=-3.7108687 where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='ctra. de carabanchel a villaverde, 54 madrid villaverde 28041';
UPDATE centro SET latitud=40.2593844, longitud=-3.699396  where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='av. juan pablo ii (esquina manuel de falla) pinto 28320';
UPDATE centro SET latitud=40.4824995, longitud=-3.3628635 where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='pl. de san diego, s/n - edificio san ildefonso alcalá de henares 28801';



--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='ctra. colmenar viejo, km. 15 madrid 28049';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='madrid, 126-128 getafe 28903';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ tulipan, s/n móstoles 28933';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='ctra. de boadilla del monte, k 5,3 boadilla del monte';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='av. poblados, s/n madrid carabanchel 28047';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='ctra. colmenar viejo, km 14,200 madrid';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ buenavista, s/n santa maría de la alameda 28296';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ arroyo fontarrón, 209 madrid moratalaz 28030';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='via de servicio a1 km 28 san sebastián de los reyes 28702';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ embalse de navacerrada c/v emb de la pinilla madrid 28051';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ sauce, sin fuenlabrada 28942';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ de miguel Ángel cantero oliva, s/n boadilla del monte 28669';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='ctra. n320, 334,5 torrelaguna 28180';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='ctra. nacional v, km. 10,600 alcorcón 28925';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ de arturo soria, 245 madrid ciudad lineal 28033';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ de la escuela de vallecas madrid villa de vallecas 28051';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ de la jacaranda madrid arganzuela 28045';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ eras de arriba, 56 navalafuente 28729';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ bolivar, 24 madrid arganzuela 28045';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ rio bidasoa, 1 alcalá de henares 28803';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='av. del ferrocarril, 17 arganda del rey 28500';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ manzanares el real, 10 boalo, el 28411';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='av. de la aviación, s/n madrid latina 28044';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='c/ de los frailes leganés 28914';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='ctra. nacional vi, km. 50,300 guadarrama 28440';
--UPDATE centro SET latitud=?, longitud=? where latitud is null and longitud is null and LOWER(TRIM(REPLACE(IFNULL(domicilio, '') || ' ' || IFNULL(municipio, '') || ' ' || IFNULL(distrito, '') || ' ' || IFNULL(cp, ''), '  ', ' ')))='ctra. m-607 colmenar viejo, k12,8 madrid fuencarral-el pardo 28049';