name: scrape
on:
  workflow_dispatch:
  schedule:
  - cron: '0 3 1 * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Autoclean
        run: sudo apt clean -y && sudo apt autoclean -y && sudo apt autoremove -y
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: Install dependencies
        run: sudo apt install libpoppler-cpp-dev
      - name: Install pip packages
        run: pip install -r requirements.txt
      - name: rm file cache
        run: rm -f cache/etapas.json cache/form.json
      - name: DWN Centros
        uses: nick-fields/retry@v2
        env:
          JS_TIMEOUT: ${{ vars.JS_TIMEOUT }}
          TCP_LIMIT: ${{ vars.TCP_LIMIT }}
        with:
          timeout_minutes: 60
          retry_wait_seconds: 15
          max_attempts: 3
          retry_on: error
          command: "rm -rf cache/csv/ && python dwn.py --centros --tcp-limit ${TCP_LIMIT:-50}"
      - name: DWN Busquedas
        uses: nick-fields/retry@v2
        env:
          JS_TIMEOUT: ${{ vars.JS_TIMEOUT }}
          TCP_LIMIT: ${{ vars.TCP_LIMIT }}
        with:
          timeout_minutes: 60
          retry_wait_seconds: 15
          max_attempts: 3
          retry_on: error
          command: "rm -rf cache/ids/ && python dwn.py --busquedas --tcp-limit ${TCP_LIMIT:-50}"
      - name: Build DB
        uses: nick-fields/retry@v2
        env:
          JS_TIMEOUT: ${{ vars.JS_TIMEOUT }}
        with:
          timeout_minutes: 60
          retry_wait_seconds: 15
          max_attempts: 3
          retry_on: error
          command: "python build.py"
      - name: Commit and push if content changed
        run: |-
          DT=$(date -u +'%Y-%m-%d %H:%M UTC')
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A 
          git commit -m "Automated: ${DT}" || exit 0
          git push
